import React, { useState, useEffect } from 'react';
import type { StoreDB } from '../services/dbInterface';
import type { 
  ItemMaster, 
  DivisionMatrix, 
  StoreRequest, 
  StoreRequestItem, 
  UserProfile
} from '../types';
import { 
  Plus, 
  Trash2, 
  ShoppingCart, 
  Eye, 
  Clock, 
  Calendar, 
  Package
} from 'lucide-react';

interface RequesterDashboardProps {
  db: StoreDB;
  profile: UserProfile;
}

interface CartItem {
  item: ItemMaster;
  quantity: number;
}

export const RequesterDashboard: React.FC<RequesterDashboardProps> = ({ db, profile }) => {
  const [requests, setRequests] = useState<StoreRequest[]>([]);
  const [itemsCatalog, setItemsCatalog] = useState<ItemMaster[]>([]);
  const [divisions, setDivisions] = useState<DivisionMatrix[]>([]);
  
  // UI States
  const [showNewRequestForm, setShowNewRequestForm] = useState(false);
  const [selectedRequest, setSelectedRequest] = useState<StoreRequest | null>(null);
  const [selectedRequestItems, setSelectedRequestItems] = useState<StoreRequestItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);

  // New Request Form States
  const [reqDivision, setReqDivision] = useState('');
  const [cart, setCart] = useState<CartItem[]>([]);
  const [selectedCatalogItemId, setSelectedCatalogItemId] = useState('');
  const [addQty, setAddQty] = useState(1);
  const [formError, setFormError] = useState('');

  useEffect(() => {
    loadData();
  }, [db, profile.email]);

  const loadData = async () => {
    setLoading(true);
    try {
      const allReqs = await db.getRequests();
      // Filter requests belonging to this requester
      const userReqs = allReqs.filter(r => r.requesterEmail.toLowerCase() === profile.email.toLowerCase());
      setRequests(userReqs);

      const catalog = await db.getItems();
      setItemsCatalog(catalog.filter(i => i.stockOnHand > 0)); // Only show items in stock

      const divs = await db.getDivisions();
      const userEmail = profile.email.toLowerCase();
      // Filter divisions where this user is explicitly listed in requesters.
      // If the user is not listed anywhere, show all divisions as a fallback.
      const assignedDivs = divs.filter(d => {
        if (!d.requesters) return false;
        const list = d.requesters.toLowerCase().split(';');
        return list.includes(userEmail);
      });
      const visibleDivs = assignedDivs.length > 0 ? assignedDivs : divs;
      setDivisions(visibleDivs);
      if (visibleDivs.length > 0) {
        setReqDivision(visibleDivs[0].title);
      }
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  const handleViewRequestDetails = async (req: StoreRequest) => {
    try {
      const items = await db.getRequestItems(req.id);
      setSelectedRequestItems(items);
      setSelectedRequest(req);
    } catch (e) {
      console.error("Error fetching request items", e);
    }
  };

  const handleAddToCart = () => {
    if (!selectedCatalogItemId) return;
    const catalogItem = itemsCatalog.find(i => i.id === selectedCatalogItemId);
    if (!catalogItem) return;

    if (addQty <= 0) {
      setFormError('Quantity must be greater than 0');
      return;
    }

    const existingIdx = cart.findIndex(c => c.item.id === catalogItem.id);
    if (existingIdx !== -1) {
      const newCart = [...cart];
      newCart[existingIdx].quantity += addQty;
      setCart(newCart);
    } else {
      setCart([...cart, { item: catalogItem, quantity: addQty }]);
    }

    setSelectedCatalogItemId('');
    setAddQty(1);
    setFormError('');
  };

  const handleRemoveFromCart = (index: number) => {
    const newCart = [...cart];
    newCart.splice(index, 1);
    setCart(newCart);
  };

  const handleCartQtyChange = (index: number, val: number) => {
    if (val <= 0) return;
    const newCart = [...cart];
    newCart[index].quantity = val;
    setCart(newCart);
  };

  const handleSubmitRequest = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!reqDivision) {
      setFormError('Please select a division');
      return;
    }
    if (cart.length === 0) {
      setFormError('Please add at least one item to your request');
      return;
    }

    setSubmitting(true);
    setFormError('');

    try {
      const totalAmount = cart.reduce((sum, c) => sum + (c.item.unitPrice * c.quantity), 0);
      
      const newRequestData = {
        requesterEmail: profile.email,
        requesterName: profile.name,
        division: reqDivision,
        totalAmount,
        auditTrail: []
      };

      const lineItems = cart.map(c => ({
        id: '', // Generated by DB provider
        requestId: '', // Linked by DB provider
        itemId: c.item.id,
        title: c.item.title,
        requestedQuantity: c.quantity,
        issuedQuantity: 0,
        itemStatus: 'Pending' as const,
        unitPrice: c.item.unitPrice,
        totalPrice: c.item.unitPrice * c.quantity
      }));

      const createdRequest = await db.createRequest(newRequestData, lineItems);

      // Trigger Workflow Email to HOD
      const selectedDiv = divisions.find(d => d.title.toLowerCase() === reqDivision.toLowerCase());
      const hodEmail = selectedDiv ? selectedDiv.hodEmail : '';
      if (hodEmail) {
        const emailSubject = `Store Request ${createdRequest.title}: Pending HOD Approval`;
        const emailBody = `
          <div style="font-family: sans-serif; max-width: 600px; padding: 20px; border: 1px solid #e2e8f0; border-radius: 8px;">
            <h2 style="color: #4f46e5; margin-bottom: 16px;">Store Request Pending Approval</h2>
            <p>Hi ${selectedDiv?.hodName || 'HOD'},</p>
            <p>A new store request <strong>${createdRequest.title}</strong> has been submitted by <strong>${profile.name}</strong> (${profile.email}) under the <strong>${reqDivision}</strong> division and is now awaiting your approval.</p>
            
            <table style="width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 14px;">
              <thead>
                <tr style="border-bottom: 2px solid #e2e8f0; text-align: left;">
                  <th style="padding: 8px 0;">Item Name</th>
                  <th style="padding: 8px 0; text-align: right;">Qty</th>
                  <th style="padding: 8px 0; text-align: right;">Unit Price</th>
                  <th style="padding: 8px 0; text-align: right;">Total Price</th>
                </tr>
              </thead>
              <tbody>
                ${cart.map(c => `
                  <tr style="border-bottom: 1px solid #edf2f7;">
                    <td style="padding: 8px 0;">${c.item.title}</td>
                    <td style="padding: 8px 0; text-align: right;">${c.quantity}</td>
                    <td style="padding: 8px 0; text-align: right;">LKR ${c.item.unitPrice.toLocaleString()}</td>
                    <td style="padding: 8px 0; text-align: right;">LKR ${(c.item.unitPrice * c.quantity).toLocaleString()}</td>
                  </tr>
                `).join('')}
              </tbody>
            </table>
            
            <div style="background: #f7fafc; padding: 12px; border-radius: 6px; font-weight: bold; font-size: 16px; text-align: right; margin-bottom: 16px; border: 1px solid #e2e8f0;">
              Total Estimated Amount: <span style="color: #4f46e5;">LKR ${totalAmount.toLocaleString()}</span>
            </div>

            <p style="margin-top: 24px;">Please sign in to the Storekeeper Portal to review, write comments, and complete your approval decision.</p>
            <hr style="border: 0; border-top: 1px solid #e2e8f0; margin-top: 24px;" />
            <p style="font-size: 11px; color: #718096; text-align: center; margin-top: 12px;">This is an automated workflow notification from your Store Request Portal.</p>
          </div>
        `;
        db.sendWorkflowEmail(hodEmail, emailSubject, emailBody).catch(err => console.error("Submit email failed", err));
      }
      
      // Reset form
      setCart([]);
      setShowNewRequestForm(false);
      await loadData();
    } catch (e) {
      console.error(e);
      setFormError('Failed to submit request. Please try again.');
    } finally {
      setSubmitting(false);
    }
  };



  const totalCartCost = cart.reduce((sum, c) => sum + (c.item.unitPrice * c.quantity), 0);

  return (
    <div className="flex-column gap-md">
      {/* Upper Action Bar */}
      <div className="flex justify-between align-center">
        <div>
          <h2 className="gradient-text shadow-text-glow" style={{ fontSize: '26px' }}>My Store Requests</h2>
          <p className="text-secondary" style={{ fontSize: '14px' }}>Submit requests, track approvals, and view items issued to you.</p>
        </div>
        <button 
          className="btn btn-primary" 
          onClick={() => {
            setShowNewRequestForm(!showNewRequestForm);
            setFormError('');
          }}
        >
          {showNewRequestForm ? 'Cancel Request' : <><Plus size={16} /> New Request</>}
        </button>
      </div>

      {showNewRequestForm ? (
        /* New Request Form Panel */
        <div className="glass-panel">
          <h3 className="margin-bottom-md flex align-center gap-sm">
            <ShoppingCart size={20} className="gradient-text" />
            Create Store Request
          </h3>

          <form onSubmit={handleSubmitRequest} className="flex-column gap-md">
            <div className="grid-cols-2">
              <div className="form-group">
                <label>Requester Details</label>
                <input 
                  type="text" 
                  className="form-control" 
                  value={`${profile.name} (${profile.email})`} 
                  disabled 
                  style={{ opacity: 0.7 }}
                />
              </div>

              <div className="form-group">
                <label>Division *</label>
                <select 
                  className="form-control" 
                  value={reqDivision} 
                  onChange={(e) => setReqDivision(e.target.value)}
                  required
                >
                  <option value="" disabled>Select Division</option>
                  {divisions.map(d => (
                    <option key={d.id} value={d.title}>{d.title}</option>
                  ))}
                </select>
              </div>
            </div>

            {/* Catalog Add Section */}
            <div className="glass-panel" style={{ background: 'rgba(0,0,0,0.15)', borderStyle: 'dashed' }}>
              <h4 className="margin-bottom-md text-secondary" style={{ fontSize: '15px' }}>Add Items from Catalog</h4>
              <div className="grid-cols-3 align-center gap-md">
                <div className="form-group" style={{ marginBottom: 0 }}>
                  <label style={{ fontSize: '12px' }}>Choose Item</label>
                  <select 
                    className="form-control" 
                    value={selectedCatalogItemId}
                    onChange={(e) => setSelectedCatalogItemId(e.target.value)}
                  >
                    <option value="">-- Choose Item --</option>
                    {itemsCatalog.map(i => (
                      <option key={i.id} value={i.id}>
                        {i.title} - LKR {i.unitPrice.toLocaleString()} ({i.stockOnHand} {i.unit}s left)
                      </option>
                    ))}
                  </select>
                </div>

                <div className="form-group" style={{ marginBottom: 0 }}>
                  <label style={{ fontSize: '12px' }}>Quantity</label>
                  <input 
                    type="number" 
                    className="form-control" 
                    value={addQty} 
                    min={1}
                    onChange={(e) => setAddQty(Math.max(1, Number(e.target.value)))}
                  />
                </div>

                <button 
                  type="button" 
                  className="btn btn-secondary" 
                  style={{ marginTop: '20px', width: '100%' }}
                  onClick={handleAddToCart}
                  disabled={!selectedCatalogItemId}
                >
                  Add to Basket
                </button>
              </div>
            </div>

            {/* Shopping Cart Lines */}
            <div>
              <h4 className="margin-bottom-md" style={{ fontSize: '15px' }}>Request Items Basket</h4>
              {cart.length === 0 ? (
                <div className="text-muted" style={{ padding: '24px', textAlign: 'center', background: 'rgba(0,0,0,0.1)', borderRadius: '8px' }}>
                  Your basket is empty. Select items from the catalog above.
                </div>
              ) : (
                <div className="item-basket">
                  {cart.map((cartItem, index) => (
                    <div className="basket-item" key={cartItem.item.id}>
                      <div>
                        <strong style={{ display: 'block', color: 'var(--text-primary)' }}>{cartItem.item.title}</strong>
                        <span className="text-muted" style={{ fontSize: '12px' }}>Category: {cartItem.item.category}</span>
                      </div>
                      <div className="text-secondary">
                        LKR {cartItem.item.unitPrice.toLocaleString()} / {cartItem.item.unit}
                      </div>
                      <div>
                        <input 
                          type="number" 
                          className="form-control" 
                          style={{ width: '80px', padding: '6px' }}
                          value={cartItem.quantity} 
                          min={1}
                          onChange={(e) => handleCartQtyChange(index, Math.max(1, Number(e.target.value)))}
                        />
                      </div>
                      <div className="text-right font-semibold" style={{ fontWeight: 600 }}>
                        Total: LKR {(cartItem.item.unitPrice * cartItem.quantity).toLocaleString()}
                      </div>
                      <button 
                        type="button" 
                        className="btn btn-danger" 
                        style={{ padding: '8px' }}
                        onClick={() => handleRemoveFromCart(index)}
                      >
                        <Trash2 size={14} />
                      </button>
                    </div>
                  ))}

                  <div className="flex justify-between align-center" style={{ borderTop: '1px solid var(--border-color)', paddingTop: '16px', marginTop: '8px' }}>
                    <span style={{ fontWeight: 600, color: 'var(--text-secondary)' }}>Total Estimated Amount:</span>
                    <span className="gradient-text" style={{ fontSize: '20px', fontWeight: 700 }}>
                      LKR {totalCartCost.toLocaleString()}
                    </span>
                  </div>
                </div>
              )}
            </div>

            {formError && (
              <div className="alert-box alert-warning">
                {formError}
              </div>
            )}

            <div className="flex justify-end gap-md">
              <button 
                type="button" 
                className="btn btn-secondary" 
                onClick={() => {
                  setCart([]);
                  setShowNewRequestForm(false);
                }}
              >
                Discard
              </button>
              <button 
                type="submit" 
                className="btn btn-primary"
                disabled={submitting || cart.length === 0}
              >
                {submitting ? 'Submitting...' : <><Plus size={16} /> Submit Store Request</>}
              </button>
            </div>
          </form>
        </div>
      ) : (
        /* Requests History Table Dashboard */
        <div className="glass-panel">
          {loading ? (
            <div style={{ padding: '40px', textAlign: 'center' }}>
              <Clock size={32} className="pulse text-muted" style={{ margin: '0 auto 12px' }} />
              <p className="text-muted">Loading your store requests...</p>
            </div>
          ) : requests.length === 0 ? (
            <div style={{ padding: '60px', textAlign: 'center' }} className="flex-column align-center gap-md">
              <Package size={48} className="text-muted" style={{ opacity: 0.5 }} />
              <div>
                <h3>No requests found</h3>
                <p className="text-muted">Submit your first store request using the button above.</p>
              </div>
            </div>
          ) : (
            <div className="table-container">
              <table className="custom-table">
                <thead>
                  <tr>
                    <th>Request Ref</th>
                    <th>Date Submitted</th>
                    <th>Division</th>
                    <th>Status</th>
                    <th className="text-right">Total Amount</th>
                    <th style={{ width: '100px' }}>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {requests.map(req => (
                    <tr key={req.id}>
                      <td><strong style={{ color: 'var(--primary)' }}>{req.title}</strong></td>
                      <td>
                        <div className="flex align-center gap-sm text-secondary">
                          <Calendar size={14} />
                          {new Date(req.requestDate).toLocaleDateString()}
                        </div>
                      </td>
                      <td>{req.division}</td>
                      <td>
                        <span className={`status-badge status-${req.status}`}>
                          {req.status.replace('_', ' ')}
                        </span>
                      </td>
                      <td className="text-right font-semibold" style={{ fontWeight: 600 }}>
                        LKR {req.totalAmount.toLocaleString()}
                      </td>
                      <td>
                        <button 
                          className="btn btn-secondary" 
                          style={{ padding: '6px 12px', display: 'flex', alignItems: 'center' }}
                          onClick={() => handleViewRequestDetails(req)}
                        >
                          <Eye size={14} /> Details
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      )}

      {/* Details Popup Modal */}
      {selectedRequest && (
        <div className="modal-overlay" onClick={() => setSelectedRequest(null)}>
          <div className="modal-content" style={{ maxWidth: '800px' }} onClick={(e) => e.stopPropagation()}>
            <div className="flex justify-between align-center" style={{ borderBottom: '1px solid var(--border-color)', paddingBottom: '12px' }}>
              <div>
                <h3 className="gradient-text">{selectedRequest.title}</h3>
                <span className="text-muted" style={{ fontSize: '12px' }}>
                  Submitted on {new Date(selectedRequest.requestDate).toLocaleString()} by {selectedRequest.requesterName}
                </span>
              </div>
              <span className={`status-badge status-${selectedRequest.status}`}>
                {selectedRequest.status.replace('_', ' ')}
              </span>
            </div>

            <div className="dashboard-layout" style={{ margin: '12px 0' }}>
              {/* Left Side: Items Requested */}
              <div className="flex-column gap-sm">
                <h4 className="text-secondary" style={{ fontSize: '15px', borderBottom: '1px solid var(--border-color)', paddingBottom: '6px' }}>Requested Items</h4>
                <div className="flex-column gap-sm" style={{ maxHeight: '250px', overflowY: 'auto', paddingRight: '6px' }}>
                  {selectedRequestItems.map(item => (
                    <div key={item.id} className="flex justify-between align-center" style={{ background: 'var(--bg-secondary)', padding: '10px', borderRadius: '6px', border: '1px solid var(--border-color)' }}>
                      <div>
                        <strong style={{ fontSize: '14px', display: 'block' }}>{item.title}</strong>
                        <span className="text-muted" style={{ fontSize: '12px' }}>
                          Price: LKR {item.unitPrice.toLocaleString()}
                        </span>
                      </div>
                      <div className="text-right">
                        <div style={{ fontSize: '14px', fontWeight: 600 }}>
                          Requested: {item.requestedQuantity}
                        </div>
                        {selectedRequest.status === 'Completed' && (
                          <div style={{ fontSize: '12px', color: item.issuedQuantity > 0 ? 'var(--color-completed)' : 'var(--color-declined)', fontWeight: 500 }}>
                            Issued: {item.issuedQuantity}
                          </div>
                        )}
                        {item.itemStatus !== 'Pending' && (
                          <span style={{ 
                            fontSize: '10px', 
                            padding: '1px 6px', 
                            borderRadius: '10px', 
                            background: item.itemStatus === 'Approved' ? 'rgba(145, 80, 45, 0.15)' : 'rgba(0, 85, 65, 0.15)',
                            color: item.itemStatus === 'Approved' ? 'var(--color-completed)' : 'var(--color-declined)',
                            fontWeight: 600,
                            textTransform: 'uppercase'
                          }}>
                            {item.itemStatus}
                          </span>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
                <div className="flex justify-between align-center" style={{ padding: '8px 12px', background: 'var(--bg-secondary)', borderRadius: '6px', marginTop: '8px' }}>
                  <span style={{ fontWeight: 600 }}>Total Request Value:</span>
                  <span className="font-semibold" style={{ fontWeight: 700, fontSize: '16px', color: 'var(--primary)' }}>
                    LKR {selectedRequest.totalAmount.toLocaleString()}
                  </span>
                </div>
              </div>

              {/* Right Side: Timeline & Comments */}
              <div className="flex-column gap-sm">
                <h4 className="text-secondary" style={{ fontSize: '15px', borderBottom: '1px solid var(--border-color)', paddingBottom: '6px' }}>Approval Progress</h4>
                <div style={{ maxHeight: '250px', overflowY: 'auto' }}>
                  <div className="timeline">
                    {selectedRequest.auditTrail.map((audit, idx) => (
                      <div className="timeline-item" key={idx}>
                        <div className="timeline-marker"></div>
                        <div className="timeline-content">
                          <div className="timeline-header">
                            <span>{audit.role} ({audit.user})</span>
                            <span>{new Date(audit.timestamp).toLocaleDateString()}</span>
                          </div>
                          <div className="timeline-title">{audit.action}</div>
                          {audit.comments && (
                            <div className="timeline-comment">"{audit.comments}"</div>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </div>

            <div className="flex justify-end" style={{ borderTop: '1px solid var(--border-color)', paddingTop: '12px' }}>
              <button className="btn btn-secondary" onClick={() => setSelectedRequest(null)}>Close Details</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
